apiVersion: v1
kind: Secret
metadata:
  name: iron-metrics-api-secret
  labels:
    app.kubernetes.io/name: iron-metrics-api
    app.kubernetes.io/part-of: iron-metrics
type: Opaque
stringData:
  IRON_METRICS_DB_PASSWORD: "iron_metrics_dev_password"
  IRON_METRICS_JWT_SECRET: "iron-metrics-minikube-local-secret-key-with-at-least-256-bits-change-me"
